export enum APP_ACTION_GROUPS {
  AUTH = "AUTH",
  ADMIN = "ADMIN",
  CLIENT = "CLIENT",
  USER = "USER",
  TASK = "TASK",
}

export enum APP_ACTIONS {
  AUTH_LOGIN = "AUTH_LOGIN",
  AUTH_REGISTER = "AUTH_REGISTER",
  ADMIN_ADD_CLIENT = "ADMIN_ADD_CLIENT",
  GET_CLIENT_META_DATA = "GET_CLIENT_META_DATA",
  UPDATE_CLIENT_TRANSLATION = "UPDATE_CLIENT_TRANSLATION",
  GET_ALL_USERS = "GET_ALL_USERS",
  ADD_USER_BY_ADMIN = "ADD_USER_BY_ADMIN",
  MARK_USER_AS_ADMIN = "MARK_USER_AS_ADMIN",
  MARK_AS_SYSTEM_ADMIN = "MARK_AS_SYSTEM_ADMIN",
  GET_TASKS = "GET_TASKS",
  GET_TASK = "GET_TASK",
  REGISTER_TASK = "REGISTER_TASK",
  UPDATE_TASK = "UPDATE_TASK",
  DELETE_TASK = "DELETE_TASK",
  ADD_NOTE = "ADD_NOTE",
  REMOVE_NOTE = "REMOVE_NOTE",
}
